# Site settings
title: Chung Poon
email: hello@cmpoon.com
url: https://portfolio.cmpoon.com
description: "Chung Poon : Engineer - Developer - Designer. Find out more about his work in his porfolio here."
keywords: "Chung Poon, porfolio, designer, web, developer, full stack"
skills: "Engineer &middot; Developer &middot; Designer"
meta_author: Poon Chung

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: cmpoon

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1869bc #80B3FF #Default 18bc9c
  primary-rgb: "24,105,188" #"128,179,255" #Default 24,288,156
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Chung Poon
  location: Imperial College London, UK
  social: Connect with me
  credits: CMPoon.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/cmpoon
  - title: github
    url: http://github.com/cmpoon
  - title: google-plus
    url: http://plus.google.com/cmpoon212


# Postal address (add as many lines as necessary)
address:
  - line: EEE Department
  - line: Imperial College
  - line: South Kensington, London
  - line: SW7 2AZ

# Credits content
credits: '<a href="https://cmpoon.com/">Home</a>&nbsp;|&nbsp;<a href="https://cmpoon.com/terms">Terms</a>&nbsp;|&nbsp;<a href="https://cmpoon.com/privacy">Privacy</a>'

# Build settings
markdown: kramdown
permalink: pretty
